### ISSUE TITLE
Configurable TCP Keep Alive Interval - Save battery

### ISSUE THREAD

**Issue by ghost** [noonien-d/telepathy-gabble#1]
Thank you for the great patches, which make it possible to use XMPP under sailfish properly!

I have the following question / suggestion: I noticed that the device sends a packet to the server every 30s to maintain the connection. This costs a lot of battery, especially for mobile data connection and is not really necessary, usually a TCP stream is maintained much longer (several minutes).

Would it be possible to make this value configurable? The code should be located in the connection.c file starting at line 1177:

  ```
g_object_class_install_property (object_class, PROP_KEEPALIVE_INTERVAL,
      g_param_spec_uint (
          "keepalive-interval", "keepalive interval",
          "Seconds between keepalive packets, or 0 to disable",
          0, G_MAXUINT, 30,
          G_PARAM_CONSTRUCT | G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
```
Unfortunately, I can not program in C and can only offer to test changes...

**Comment by noonien-d** [comment]
Hi Thomas,
I did not test the impact, but 
`mc-tool update gabble/jabber/jabber_1 uint:keepalive-interval=60`
should set exactly this parameter.
